[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mdipplcloud"
version = "0.2.1"
description = "Pupil Labs Cloud API Wrapper"
readme = "README.md"
authors = [
    { name = "Martin Schulte-Ruether", email = "martin@schulte-ruether.de" }
]
license = { text = "MIT" }
dependencies = [
    "requests"
]
requires-python = ">=3.8"

[project.urls]
homepage = "https://github.com/msrresearch/mdipplcloud"
repository = "https://github.com/msrresearch/mdipplcloud"

[project.entry-points."mdivicomtools.plugins"]
mdipplcloud = "mdipplcloud.plugin:get_plugin"

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
include = ["mdipplcloud*"]
exclude = ["planning*", "docs*", "scripts*"]
